import pytest
import requests

URL = "https://flask-ml-service-v2.azurewebsites.net:443/predict"

def test_app_post_request():
    """Assure we get a 200 response back from POST request"""

    data = {
        "plusMinus": {
            "0": -4,
            "1": -7,
            "2": 0,
            "3": 13,
            "4": -27,
            "5": -2,
            "6": -11,
            "7": 0,
            "8": -20,
            "9": 27,
        },
        "Position": {
            "0": "D",
            "1": "LW",
            "2": "D",
            "3": "LW",
            "4": "C",
            "5": "RW",
            "6": "C",
            "7": "C",
            "8": "D",
            "9": "C",
        },
        "G": {
            "0": 0,
            "1": 2,
            "2": 0,
            "3": 27,
            "4": 15,
            "5": 0,
            "6": 17,
            "7": 0,
            "8": 14,
            "9": 30,
        },
        "A1": {
            "0": 1,
            "1": 1,
            "2": 0,
            "3": 9,
            "4": 13,
            "5": 0,
            "6": 23,
            "7": 0,
            "8": 14,
            "9": 44,
        },
        "GP": {
            "0": 36,
            "1": 20,
            "2": 1,
            "3": 81,
            "4": 82,
            "5": 7,
            "6": 79,
            "7": 4,
            "8": 72,
            "9": 82,
        },
        "Grit": {
            "0": 139,
            "1": 13,
            "2": 2,
            "3": 316,
            "4": 54,
            "5": 9,
            "6": 69,
            "7": 0,
            "8": 199,
            "9": 89,
        },
        "TOI%": {
            "0": 23.8,
            "1": 24.6,
            "2": 35.8,
            "3": 30.0,
            "4": 32.3,
            "5": 17.4,
            "6": 30.3,
            "7": 17.4,
            "8": 39.3,
            "9": 35.3,
        },
        "xGA": {
            "0": 24.3,
            "1": 10.3,
            "2": 1.1,
            "3": 53.2,
            "4": 58.3,
            "5": 2.2,
            "6": 46.2,
            "7": 1.5,
            "8": 65.2,
            "9": 69.7,
        },
        "xGF": {
            "0": 16.7,
            "1": 11.9,
            "2": 0.3,
            "3": 82.0,
            "4": 69.5,
            "5": 4.1,
            "6": 81.0,
            "7": 1.1,
            "8": 76.9,
            "9": 115.7,
        },
        "First Name": {
            "0": "Alex",
            "1": "Kyle",
            "2": "Chris",
            "3": "Patrick",
            "4": "Henrik",
            "5": "Nicklas",
            "6": "Sam",
            "7": "Chandler",
            "8": "Mike",
            "9": "Connor",
        },
        "Last Name": {
            "0": "Biega",
            "1": "Connor",
            "2": "Butler",
            "3": "Maroon",
            "4": "Sedin",
            "5": "Jensen",
            "6": "Reinhart",
            "7": "Stephenson",
            "8": "Green",
            "9": "McDavid",
        },
        "Team": {
            "0": "VAN",
            "1": "WPG",
            "2": "STL",
            "3": "EDM",
            "4": "VAN",
            "5": "NYR",
            "6": "BUF",
            "7": "WSH",
            "8": "DET",
            "9": "EDM",
        },
    }
    headers = {"Content-Type": "application/json"}
    r = requests.post(URL, json=data, headers=headers)

    assert r.status_code == 200