name: Simple Azure Flask Web App | Python 3.12

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run:
        make install
    - name: Lint with ruff
      run:
        make lint
    - name: Test with pytest
      run: 
        make test
